name: CI - Full-Stack App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-devsecops-app .

      - name: Test Application Startup
        run: docker run --rm my-devsecops-app python -c "from app import app"

      - name: Run Bandit Linter
        run: docker run --rm my-devsecops-app bandit -r . -x ./venv

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-devsecops-app'
          scan-type: 'image'
          security-checks: 'vuln'
          severity: 'HIGH'
          format: 'table'

      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RENDER_API_DEPLOY_HOOK_URL: ${{ secrets.RENDER_API_DEPLOY_HOOK_URL }}
        run: curl -X POST $RENDER_API_DEPLOY_HOOK_URL